name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  build-client:
    name: Build and Deploy Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Add VERCEL_TOKEN in GitHub Secrets
          vercel-args: '--prod'
          working-directory: ./client
          vercel-project-name: your-vercel-project-name
          vercel-org-id: your-vercel-org-id
          vercel-team-id: your-vercel-team-id # Optional, if working with a team

  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} # Add HEROKU_API_KEY in GitHub Secrets
          heroku_app_name: your-heroku-app-name
          heroku_email: your-heroku-email
