name: Deploy MERN App to Local Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      # Set the legacy OpenSSL provider to fix the build error
      - name: Set environment variable for OpenSSL provider
        run: |
          echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
      
      - name: Install dependencies for Backend
        run: |
          cd mern-app-server
          npm install
      
      - name: Install dependencies for Frontend
        run: |
          cd mern-app-client
          npm install

      - name: Build Frontend
        run: |
          cd mern-app-client
          npm run build

      - name: Deploy Backend
        run: |
          cd mern-app-server
          npm start
